# Copyright (C) 2018 NVIDIA Corporation.  All rights reserved.
# Licensed under the CC BY-NC-SA 4.0 license (https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode).

# logger options
image_save_iter: 1000          # How often do you want to save output images during training
image_display_iter: 1000       # How often do you want to display output images during training
display_size: 4             # How many images do you want to display each time
snapshot_save_iter: 10000      # How often do you want to save trained models
log_iter: 10                  # How often do you want to log the training stats

# optimization options
max_iter: 400000             # maximum number of training iterations
batch_size: 8                 # batch size
weight_decay: 0.0001          # weight decay
beta1: 0.5                    # Adam parameter
beta2: 0.999                  # Adam parameter
init: kaiming                 # initialization [gaussian/kaiming/xavier/orthogonal]
lr: 0.0001                    # initial learning rate
lr_policy: step               # learning rate scheduler
step_size: 100000             # how often to decay learning rate
gamma: 0.5                    # how much to decay learning rate
adv_w: 1
adv_c_w: 1
rec_w: 10
rec_s_w: 10
rec_c_w: 10
cla_w: 10
cyc_w: 10
kld_w: 1      
gen:
  dim: 64                     # number of filters in the bottommost layer
  mlp_dim: 256                # number of filters in MLP
  noise_dim: 8                # length of style code
  activ: relu                 # activation function [relu/lrelu/prelu/selu/tanh]
  n_downsample: 2             # number of downsampling layers in content encoder
  n_res: 4                    # number of residual blocks in content encoder/decoder
  pad_type: reflect           # padding type [zero/reflect]
  selected_attrs: [Black_Hair, Blond_Hair, Brown_Hair, Male, Young, Smiling, Eyeglasses, Goatee]
                              #selected attributes
dis:
  dim: 64                     # number of filters in the bottommost layer
  norm: none                  # normalization layer [none/bn/in/ln]
  activ: lrelu                # activation function [relu/lrelu/prelu/selu/tanh]
  n_layer: 5                  # number of layers in D
  num_scales: 3               # number of scales
  pad_type: reflect           # padding type [zero/reflect]

# data options
input_dim: 3                  # number of image channels
new_size: 128                 # first resize the shortest image side to this size
crop_image_height: 128        # random crop image of this height
crop_image_width: 128         # random crop image of this width
data_root: /home/lxy/multi-label/datasets/face512/  # dataset folder location
label_root: /home/lxy/multi-label/datasets/face/train.txt
                              # label folder location
